### PR TITLE
Update to ofono 1.27

### PR DESCRIPTION
**Pull request by piggz**
This builds on the 1.26 PR and adds the small handful of patches to bring up to 1.27

### CODE REVIEW

**Comment by monich** [comment]
Needs a rebase

**Comment by piggz** [comment]
Rebased :) thanks for fixing those small issues .. im deep into trying to get the Pinephone driver working :)

**Review by monich — APPROVED** [review]
Looks safe

**Comment by monich** [comment]
Thanks!

**Pull request merged**
