### PR TITLE
WIP: [ofono] Add D-Bus signals for filtered calls.

### PR DESCRIPTION
**Pull request by dcaliste**
Expose over D-Bus the result of the call filtering.

### CODE REVIEW

**Comment by dcaliste** [comment]
Hello @monich, thank you for commenting. May I give a bit more arguments than the few lines of the PR:
- as far as I understand, there may be several filtering plugins (like an mdm one and a user-chosen one for instance) and the logic in `voicecall.c` has the final word on what is blocked and what is not blocked (or ignored). So if a call is filtered out, it's known at oFono level and not only in the plug-in.
- oFono is doing actions, like receiving a call or terminating it and is signaling on D-Bus what happens. A filtered call is in my opinion, an action in the same sense than receiving a call, thus the signaling from the voicecall manager in that PR. If the user land wants the filtered calls to be completely ignored, it can just not connect to the signal.
- with filtering, I see the action of ignoring / blocking a call as a concept at oFono level and not a per-plugin one. Doing so allow to integrate such concept in other layers of the system, like the call history for instance. Then everyone can benefit of such information and just implement another filtering plugin without bothering about creating yet another application to list history of blocked calls.

I'm very glad that you introduced this filtering API, and I'm now using it in a home-made plugin: https://github.com/dcaliste/ofono-voicecall-filter-plugin . I can very easily filter out annoying calls. I would like to be able to monitor what happens though.

You may still disagree with my reasoning. In that case, I can, as you suggest, put the D-Bus signaling in the plug-in itself and handle the history listing in a dedicated application with a dedicated history database.

**Comment by monich** [comment]
Well, in most cases you would still need a separate application, settings plugin or some sort of UI to manage the behavior of the filtering plugin. The same (or separate) UI would likely have a history too, with some additional plugin-specific details or actions for each event. The additional system-provided UI (quite a primitive one, because of lack of information about what's actually happened and why) would only confuse the user by listing the same events in another place in a different way.

On the other hand, it's quite possible that some primitive plugins without any UI of their own may benefit from this feature. The fact that you're suggesting it, kind of proves it (although you may change your opinion if you actually try to implement such a plugin)

If you feel sure that there will be some use for it, then at least make it a per-plugin opt-in feature - to avoid the behavior changes for already exiting plugins, and to support plugins that for whatever reason need to be quiet. In other words, if the plugin which blocks the call doesn't express the wish to log its activity by calling some ofono function, then ofono should stay quiet.

**Comment by monich** [comment]
I sort of had in mind white/blacklist call/sms plugins (not just MDM) when I was designing those filtering interfaces.

The filtering operations were allowed to be asynchronous, assuming that such a plugin would just make an asynchronous cancelable D-Bus call and the real job would be done by the D-Bus daemon process (on-demand, like mms-daemon), which would provide one (system bus) interface for the ofono filtering plugin and another one (on the session bus) for the UI. That daemon (running as a privileged user process) would synchronize and control the access to the history database, manage the settings and implement the filtering logic.

I hope this makes it clearer why things were done the way they were done.

**Comment by dcaliste** [comment]
Thanks again for the discussion. I've seen the async API and was thinking that it can be used for something like what you described. I didn't go that route first because it seemed more complicated. But after I wrote the plugin I already mentioned, using a GSettings to store the white / black list, I noticed that oFono run as root and thus had trouble to get the GSettings of the user. Which can be solved by running a daemon as user, talking to a D-Bus plugin.

Anyway, I'm going to implement it the way you propose, it's better and cleaner.

**Comment by monich** [comment]
It's safer too - the less code is executed in the context of the ofono process, the better.

**Comment by dcaliste** [comment]
For what it's worth, I've implemented a plugin contacting via D-Bus a user daemon, blocking or not numbers based on string matching stored in DConf, see https://github.com/dcaliste/sailfish-voicecall-filter Feel free to give a look and give feedback, in the case you're interested in.

Now that the basics is working, I'm going to see how to log this with commhistory. Thank you @monich for the advices.

**Comment by dcaliste** [comment]
With the above mentioned implementation and https://github.com/sailfishos/libcommhistory/pull/10, it's possible to achieve the same purpose as the original one of this PR. So closing it.

**Pull request closed without merging**
