### PR TITLE
Make more APIs available to external plugins

### PR DESCRIPTION
**Pull request by monich**
This allows to build Jolla ril driver as an external dynamically loadable plugin. The actual split will be done a bit later as a separate step.

### CODE REVIEW

**Comment by monich** [comment]
Rebased

**Review by inzanity — APPROVED** [review]
I've now read it through; I'm a bit hesitant on the move from connman style (struct foo_bar) to GLib-ish style (typedef'd FooBar), as now the two styles are mixed under src/ (not just in plugins), but I guess we can live with that.

I guess we could update the doc/coding-style.txt too, especially if we expect community contributions.

All in all, looks quite sane to me, the one g_free() wrapper looks a bit unnecessary, but if there's some future plan that it could do something else, then sure.

**Comment by monich** [comment]
> All in all, looks quite sane to me, the one g_free() wrapper looks a bit unnecessary, but if there's some future plan that it could do something else, then sure.

If by g_free() wrapper you mean `ofono_sim_string_free()` then it's because the same allocator must be used for allocating and freeing the memory, and `<ofono/misc.h>` API is glib-free.

**Comment by monich** [comment]
Rebased and re-tested.

**Pull request merged**
